### ISSUE TITLE
Derived values report

### ISSUE THREAD

**Issue by Craig44** [alistairdunn1/CASAL2#106]
A Run mode that is analogous to -r with the purpose of reporting a table of derived model values e.g SSB, From a given set of parameters such as a -i file (mcmc output).

We talked about maybe using asserts for the report,

with the options being label all potential derived quantities as registerasestimable()
a new registerasvisible().

Or hard coded report which does multiple tables e.g a table for SSB, and a table for catches 

command line syntax could be, 
CASAL2 -i filename --tabular

this will only print the tabular report.

CASAL uses the following command 

CASAL -i filename  -v

**Comment by Craig44** [comment]
Alistair we need to make a decision on whether we want to use asserts for this report. We discussed creating a registerAsVisible() or registering derived  quantities as reigsterasestimable()

**Comment by Craig44** [comment]
also if @Zaita you had any major pros or cons to either of the above methods. My understanding is that they essentially will be the same.

**Comment by Zaita** [comment]
RegisterAsEstimable() is 100x quicker than RegisterAsVisible(). It also allows us to estimate/profile derived quantities

**Comment by alistairdunn1** [comment]
RegisterAsEstimable()
