### ISSUE TITLE
Process specific reporting

### ISSUE THREAD

**Issue by Craig44** [alistairdunn1/CASAL2#109]
We want to populate containers whilst executing process that get reported at the end of model run. an example of output from  two processes are attached
[Reporting spec.txt](https://github.com/alistairdunn1/CASAL2/files/38315/Reporting.spec.txt)

**Comment by Zaita** [comment]
This has been implemented and can be used in two different ways:
1)
@report.type = process

2)
@process.type = any
print_report t

Inside the code you can store values with
StoreForReport(label, value(s));
