### ISSUE TITLE
need business rule for intialisation type Cinitial

### ISSUE THREAD

**Issue by Craig44** [alistairdunn1/CASAL2#113]
Need a simple business rule saying that intialisation type Cinitial can only occur if an iterative or derived initialization has occurred prior

**Comment by Craig44** [comment]
The business rule. 
Initialization phase of type "Cinitial" can only be executed if there is another initialization phase executed before and that the intitialisation phase executed prior is of type derived or iterative

**Comment by Zaita** [comment]
Done.
