### ISSUE TITLE
Allow variable transformations in @estimates

### ISSUE THREAD

**Issue by alistairdunn1** [alistairdunn1/CASAL2#32]
Allow for variables to be transformed in estimation, i.e.if estimating "process[recruitment].r0" then the estimate block may be

@estimate 
parameter @estimate[recruitment].r0
lower_bound 1e5
upper_bound 1e7
prior uniform
transformation log

would pass log(r0) to the estimator, not r0. Bounds would be applied in natural space.

The following simple transformations should be allowed
log = log(x)
inverse = 1/x
sqrt = sqrt(x)

and more complex types that take another parameter

multiply_by = multiplies by another estimable parameter e.g.. multiplies_by process[mortality].m 
divide_by = divides by another estimable parameter e.g.. divide_by process[mortality].m
mean = estimates the mean of 2or more parameters 
diff = estimates the difference between 2 or more parameters. if estimating x1, and diff x2 x3, then implement as if estimating (x1-x2) and (x1-x3) 
box-cox = box-cox transformation (requires the parameter lambda), where box-cox(x)= (x^lambda - 1)/lambda

**Comment by Craig44** [comment]
in transformation.h we need to add 
virtual Double              Jocabian(Double initial_value) = 0;
That each transformation needs to calculate. this result needs to be passed as a component to the objective_function.

**Comment by Craig44** [comment]
@estimate_transformation transformation_label
type log
parameter (if bivariate or above) mulitpy, Divide


@estimate label
type
transformation transformation_label
